[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "fitzgen's art"
documentation = "https://docs.rs/fart"
edition = "2018"
license = "MIT/Apache-2.0"
name = "fart"
readme = "./README.md"
repository = "https://github.com/fitzgen/fart"
version = "0.3.0"

[dependencies]
euclid = "0.19.8"
failure = "0.1.5"
fart-2d-geom = { version = "=0.3.0", path = "crates/2d-geom" }
fart-aabb = { version = "=0.3.0", path = "crates/aabb" }
fart-utils = { version = "=0.3.0", path = "crates/utils" }
id-arena = "2.2.1"
noise = "0.5.1"
num-traits = "0.2.6"
rand = "0.6.5"
svg = "0.5.12"

[workspace]
members = ["crates/cli"]
