[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "CLI tool for the `fart` framework"
edition = "2018"
license = "MIT/Apache-2.0"
name = "fart-cli"
readme = "../../README.md"
repository = "https://github.com/fitzgen/fart"
version = "0.3.0"

[[bin]]
name = "fart"
path = "src/main.rs"

[dependencies]
chrono = "0.4.9"
failure = "0.1.6"
notify = "4.0.13"
structopt = "0.3.3"
tide = "0.2.0"
futures-preview = "0.3.0-alpha.19"
serde = "1"
serde_json = "1"
bytes = "0.4"
http-service = "0.3"
tokio = "0.1.22"

[dev-dependencies]
assert_cmd = "0.11.1"
predicates = "1.0.1"
quickcheck = "0.9.0"
tempfile = "3.0.7"
